### ISSUE TITLE
-Dl argument bug

### ISSUE THREAD

**Issue by NapInFever** [bellingcat/likee-downloader#10] opened 2023-09-18 15:47 UTC
**Describe the bug**
I encountered an error while trying to download the video. When I put -dl argument it shows the following error:

Downloading: 7280114956722142918_опять выгнали?😣.mp4 ----------------------------------------   0% -:--:--
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Scripts\likee_downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\downloader.py", line 57, in start_downloader
    api.download_video(video_data=video, username=username)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 204, in download_video
    with open(
         ^^^^^
OSError: [Errno 22] Invalid argument: "likee-downloader\\andriukhina\\videos\\7280114956722142918_'опять выгнали?😣'.mp4"

When I used 1.6.0 version I could at least download about 40 videos from the same channel. Would appreciate if you can look into it

**To Reproduce**
C:\Users\Alex>likee_downloader andriukhina -dl

likee-downloader v1.7.0 Copyright (C) 2022-2023  Richard Mwewa

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Obtaining userId (andriukhina)... Please wait.
userId obtained: 1064206022
Getting 10 videos... Please wait.

Post #1 ЕЁ ЛУЧШИЙ ДРУГ😍
├── avatar: https://img.like.video/eu_live/3u2/0sQ5He.jpg
├── commentCount: 34
├── coverUrl: https://videosnap.like.video/eu_live/9uI/1WoEvq_4.jpg?wmk_sdk=1&type=8
├── likeCount: 192
├── likeeId: andriukhina
├── msgText: блогеры поймут☺️//мой телеграм @andriukhinavasilisa
├── musicName: Dima Marov
├── musicId:
├── nickname: Vasilisa
├── yyuid: 357635849
├── postId: 7280117443508207302
├── shareUrl:
├── title: ЕЁ ЛУЧШИЙ ДРУГ😍
├── shareCount: 2
├── playCount: 1713
├── videoHeight: 1920
├── videoUrl: https://video.like.video/eu_live/9uO/0GkMIM_4.mp4?crc=101917478&type=5
├── videoWidth: 1080
├── hashtagInfos: [{"ev_id":"6448576556507785151","ev_tp":"1","hs_tg":"Dialog","wb_url":""}]
├── atUserInfos: []
├── label:
├── postTime: 1695034430
├── sound: {'avatar': 'https://img.like.video/eu_live/3u1/36gN75.jpg', 'ownerName': 'Dima Marov', 'soundId': '2984778341045817846', 'soundName': ''}
├── cloudMusic: None
├── pgc: {"model":"authentication_title_new_25","type":"7","url":""}
├── posterUid: 1064206022
├── checkStatus: 0
├── country: RU
├── allImage:
├── music: None
├── postType: 0
├── postLongDesc:
├── postLongHashtagInfos: []
├── postLongAtUserInfos: []
└── Sound
    ├── avatar: https://img.like.video/eu_live/3u1/36gN75.jpg
    ├── ownerName: Dima Marov
    ├── soundId: 2984778341045817846
    └── soundName:
Downloading: 7280117443508207302_ЕЁ ЛУЧШИЙ ДРУГ😍.mp4 ---------------------------------------- 100% 0:00:00
Downloaded: likee-downloader\andriukhina\videos\7280117443508207302_'ЕЁ ЛУЧШИЙ ДРУГ😍'.mp4

Post #2 выгнали⁉️
├── avatar: https://img.like.video/eu_live/3u2/0sQ5He.jpg
├── commentCount: 26
├── coverUrl: https://videosnap.like.video/eu_live/9uQ/2N6oXN_4.jpg?wmk_sdk=1&type=8
├── likeCount: 220
├── likeeId: andriukhina
├── msgText: что мне делать⁉️
├── musicName: Frosiaak
├── musicId:
├── nickname: Vasilisa
├── yyuid: 357635849
├── postId: 7280115953154555590
├── shareUrl:
├── title: выгнали⁉️
├── shareCount: 2
├── playCount: 1382
├── videoHeight: 1920
├── videoUrl: https://video.like.video/eu_live/9uF/1CuiN7_4.mp4?crc=1047855325&type=5
├── videoWidth: 1080
├── hashtagInfos: [{"ev_id":"6448576556507785151","ev_tp":"1","hs_tg":"Dialog","wb_url":""}]
├── atUserInfos: []
├── label:
├── postTime: 1695034083
├── sound: {'avatar': 'https://img.like.video/eu_live/3u1/1ezgVC.jpg', 'ownerName': 'Frosiaak ', 'soundId': '2975162462445496942', 'soundName': ''}
├── cloudMusic: None
├── pgc: {"model":"authentication_title_new_25","type":"7","url":""}
├── posterUid: 1064206022
├── checkStatus: 0
├── country: RU
├── allImage:
├── music: None
├── postType: 0
├── postLongDesc:
├── postLongHashtagInfos: []
├── postLongAtUserInfos: []
└── Sound
    ├── avatar: https://img.like.video/eu_live/3u1/1ezgVC.jpg
    ├── ownerName: Frosiaak
    ├── soundId: 2975162462445496942
    └── soundName:
Downloading: 7280115953154555590_выгнали⁉️.mp4 ---------------------------------------- 100% 0:00:00
Downloaded: likee-downloader\andriukhina\videos\7280115953154555590_'выгнали⁉️'.mp4

Post #3 опять выгнали?😣
├── avatar: https://img.like.video/eu_live/3u2/0sQ5He.jpg
├── commentCount: 38
├── coverUrl: https://videosnap.like.video/eu_live/9uE/2ABkFm_4.jpg?wmk_sdk=1&type=8
├── likeCount: 169
├── likeeId: andriukhina
├── msgText: кто рад - ❤️,кто не рад - 💬
├── musicName: Vasilisa
├── musicId:
├── nickname: Vasilisa
├── yyuid: 357635849
├── postId: 7280114956722142918
├── shareUrl:
├── title: опять выгнали?😣
├── shareCount: 1
├── playCount: 1567
├── videoHeight: 1920
├── videoUrl: https://video.like.video/eu_live/9u3/1EN3lC_4.mp4?crc=1034409127&type=5
├── videoWidth: 1080
├── hashtagInfos: [{"ev_id":"6448576556507785151","ev_tp":"1","hs_tg":"Dialog","wb_url":""}]
├── atUserInfos: []
├── label:
├── postTime: 1695033851
├── sound: {'avatar': 'https://img.like.video/eu_live/3u2/0sQ5He.jpg', 'ownerName': 'Vasilisa', 'soundId': '2985147660722142918', 'soundName': ''}
├── cloudMusic: None
├── pgc: {"model":"authentication_title_new_25","type":"7","url":""}
├── posterUid: 1064206022
├── checkStatus: 0
├── country: RU
├── allImage:
├── music: None
├── postType: 0
├── postLongDesc:
├── postLongHashtagInfos: []
├── postLongAtUserInfos: []
└── Sound
    ├── avatar: https://img.like.video/eu_live/3u2/0sQ5He.jpg
    ├── ownerName: Vasilisa
    ├── soundId: 2985147660722142918
    └── soundName:
Downloading: 7280114956722142918_опять выгнали?😣.mp4 ----------------------------------------   0% -:--:--
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Scripts\likee_downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\downloader.py", line 57, in start_downloader
    api.download_video(video_data=video, username=username)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 204, in download_video
    with open(
         ^^^^^
OSError: [Errno 22] Invalid argument: "likee-downloader\\andriukhina\\videos\\7280114956722142918_'опять выгнали?😣'.mp4"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rly0nheart** [comment] 2023-09-18 16:38
Hm let me look at this again

**Comment by rly0nheart** [comment] 2023-09-18 16:51
@NapInFever install the new release (1.7.1) and then try to download the videos.

**Comment by NapInFever** [comment] 2023-09-18 19:37
hey, i tested this prompt multiple times. Sometimes they work, sometimes they don't. I am not sure what causes the problem. My hypothesis is that the error happen when I am surfing the internet.


I am giving examples of what erorrs I had encountered in 1.7.2 after I did a clean install : 

**C:\Users\Alex>likee_downloader -dl -l 50 andriukhina**

likee-downloader v1.7.2 Copyright (C) 2022-2023  Richard Mwewa

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Obtaining userId (andriukhina)... Please wait.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Scripts\likee_downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\downloader.py", line 46, in start_downloader
    user_id = api.get_user_id(username=username)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 130, in get_user_id
    f"{self.user_profile_url % username}/video/{self.get_video_id(username=username)}"
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 105, in get_video_id
    self.driver.get(self.user_profile_url % username)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 353, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Navigation timed out after 300000 ms
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
TimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:675:5
bail@chrome://remote/content/marionette/sync.sys.mjs:211:19

Another prompt with differenet settings. I use 2 times. 1 time it worked and 1 time it showed me an error

**C:\Users\Alex>likee_downloader -dl -l 10 andriukhina**

likee-downloader v1.7.2 Copyright (C) 2022-2023  Richard Mwewa

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Obtaining userId (andriukhina)... Please wait.
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Scripts\likee_downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\downloader.py", line 46, in start_downloader
    user_id = api.get_user_id(username=username)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\likee_downloader\api.py", line 129, in get_user_id
    response = requests.get(
               ^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

**Comment by rly0nheart** [comment] 2023-09-19 02:18
Those are connection-related errors, so the problem is likely on your end. So I guess I should close this issue now?

**Closed** 2023-09-19 02:26 UTC
